# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-03-28 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('authur', models.CharField(max_length=128)),
                ('pictureName', models.CharField(max_length=64)),
                ('mentionedTimes', models.IntegerField()),
                ('type', models.CharField(max_length=32)),
                ('introduction', models.TextField()),
                ('jd', models.CharField(max_length=512)),
                ('dangdang', models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catogray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32, unique=True)),
            ],
        ),
    ]
